<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <RestoreSuccess Condition=" '$(RestoreSuccess)' == '' ">True</RestoreSuccess>
    <RestoreTool Condition=" '$(RestoreTool)' == '' ">NuGet</RestoreTool>
    <ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">$(MSBuildThisFileDirectory)project.assets.json</ProjectAssetsFile>
    <NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
    <NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">C:\Users\rdavi\.nuget\packages\;C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages</NuGetPackageFolders>
    <NuGetProjectStyle Condition=" '$(NuGetProjectStyle)' == '' ">PackageReference</NuGetProjectStyle>
    <NuGetToolVersion Condition=" '$(NuGetToolVersion)' == '' ">7.0.0</NuGetToolVersion>
  </PropertyGroup>
  <ItemGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <SourceRoot Include="C:\Users\rdavi\.nuget\packages\" />
    <SourceRoot Include="C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages\" />
  </ItemGroup>
  <ItemGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.Bcl.AsyncInterfaces.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.Bcl.AsyncInterfaces.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\Microsoft.Bcl.AsyncInterfaces.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\Microsoft.Bcl.AsyncInterfaces.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.Build.Locator.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.Build.Locator.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\Microsoft.Build.Locator.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\Microsoft.Build.Locator.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.IO.Redist.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\Microsoft.IO.Redist.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\Microsoft.IO.Redist.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\Microsoft.IO.Redist.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Buffers.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Buffers.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\System.Buffers.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\System.Buffers.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Collections.Immutable.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Collections.Immutable.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\System.Collections.Immutable.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\System.Collections.Immutable.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.IO.Pipelines.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.IO.Pipelines.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\System.IO.Pipelines.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\System.IO.Pipelines.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Memory.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Memory.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\System.Memory.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\System.Memory.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Numerics.Vectors.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Numerics.Vectors.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\System.Numerics.Vectors.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\System.Numerics.Vectors.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Runtime.CompilerServices.Unsafe.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Runtime.CompilerServices.Unsafe.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\System.Runtime.CompilerServices.Unsafe.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\System.Runtime.CompilerServices.Unsafe.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Text.Encodings.Web.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Text.Encodings.Web.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\System.Text.Encodings.Web.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\System.Text.Encodings.Web.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Text.Json.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Text.Json.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\System.Text.Json.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\System.Text.Json.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Threading.Tasks.Extensions.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.Threading.Tasks.Extensions.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\System.Threading.Tasks.Extensions.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\System.Threading.Tasks.Extensions.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.ValueTuple.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-net472\System.ValueTuple.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-net472\System.ValueTuple.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-net472\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-net472\System.ValueTuple.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-netcore\Microsoft.Build.Locator.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-netcore\Microsoft.Build.Locator.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-netcore\Microsoft.Build.Locator.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-netcore\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-netcore\Microsoft.Build.Locator.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json</TargetPath>
      <DestinationSubDirectory>BuildHost-netcore\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-netcore\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json</TargetPath>
      <DestinationSubDirectory>BuildHost-netcore\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-netcore\System.Collections.Immutable.dll" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.workspaces.msbuild\5.3.0\contentFiles\any\any\BuildHost-netcore\System.Collections.Immutable.dll')">
      <NuGetPackageId>Microsoft.CodeAnalysis.Workspaces.MSBuild</NuGetPackageId>
      <NuGetPackageVersion>5.3.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>BuildHost-netcore\System.Collections.Immutable.dll</TargetPath>
      <DestinationSubDirectory>BuildHost-netcore\</DestinationSubDirectory>
      <Private>True</Private>
      <Link>BuildHost-netcore\System.Collections.Immutable.dll</Link>
    </Content>
  </ItemGroup>
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)microsoft.codeanalysis.analyzers\5.3.0-2.25625.1\buildTransitive\Microsoft.CodeAnalysis.Analyzers.props" Condition="Exists('$(NuGetPackageRoot)microsoft.codeanalysis.analyzers\5.3.0-2.25625.1\buildTransitive\Microsoft.CodeAnalysis.Analyzers.props')" />
    <Import Project="$(NuGetPackageRoot)microsoft.build.locator\1.11.2\buildTransitive\Microsoft.Build.Locator.props" Condition="Exists('$(NuGetPackageRoot)microsoft.build.locator\1.11.2\buildTransitive\Microsoft.Build.Locator.props')" />
  </ImportGroup>
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <PkgMicrosoft_CodeAnalysis_Analyzers Condition=" '$(PkgMicrosoft_CodeAnalysis_Analyzers)' == '' ">C:\Users\rdavi\.nuget\packages\microsoft.codeanalysis.analyzers\5.3.0-2.25625.1</PkgMicrosoft_CodeAnalysis_Analyzers>
  </PropertyGroup>
</Project>